name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
      - name: Full-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
      - name: Icons
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.topics.icons.svg
          token: NOT_NEEDED
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
      - name: topic Labels
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.topics.svg
          token: NOT_NEEDED
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 12
      - uses: lowlighter/metrics@latest
        with:
          plugin_languages: yes
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_languages_sections: most-used, recently-used
          plugin_languages_recent_load: 1000
          plugin_languages_recent_days: 365
          plugin_languages_details: lines, bytes-size, percentage
      - name: Midly interesting facts
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.habits.facts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_days: 30
          config_timezone: Europe/GMT
      - name: Using classic charts
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.stargazers.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_stargazers: yes
      - name: Using chartist charts
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.stargazers.chartist.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_stargazers: yes
          plugin_stargazers_charts_type: chartist
      - name: Top answers from stackoverflow
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.stackoverflow.svg
          token: NOT_NEEDED
          base: ""
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 19471232
          plugin_stackoverflow_sections: answers-top
          plugin_stackoverflow_limit: 2
      - name: Stock prices from Tesla
        uses: lowlighter/metrics@latest
        with:  
        filename: metrics.plugin.stock.svg
        token: NOT_NEEDED
        base: ""
        plugin_stock: yes
        plugin_stock_token: ${{ secrets.STOCK_TOKEN }}
        plugin_stock_symbol: TSLA
  
